openapi: 3.0.1
info:
  description: CRUD operations to manage lists and list memberships
  title: Lists
  version: v3
  x-hubspot-product-tier-requirements:
    marketing: STARTER
    cms: STARTER
  x-hubspot-documentation-banner: NONE
  x-hubspot-api-use-case: "You want to bulk add contacts to a particular list, or\
    \ remove company records from a company list."
  x-hubspot-related-documentation:
  - name: Lists Overview
    url: https://developers.hubspot.com/docs/api/crm/lists
  x-hubspot-introduction: "Use the lists API to manage list memberships for contact,\
    \ company, and custom object lists."
servers:
- url: https://api.hubapi.com
tags:
- description: ""
  name: Lists
  x-hubspot-tag-name-english-source: Lists
- description: ""
  name: Memberships
  x-hubspot-tag-name-english-source: Memberships
paths:
  /crm/v3/lists/{listId}/update-list-name:
    put:
      description: Update the name of a list. The name must be globally unique relative
        to all other public lists in the portal.
      operationId: UpdateName
      security:
      - private_apps:
        - crm.lists.read
        - crm.lists.write
      - oauth2:
        - crm.lists.read
        - crm.lists.write
      summary: Update List Name
      tags:
      - Lists
  /crm/v3/lists/{listId}/memberships/add-and-remove:
    put:
      description: |-
        Add and/or remove records that have already been created in the system to and/or from a list.

        This endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.
      operationId: AddAndRemoveMemberships
      security:
      - private_apps:
        - crm.lists.read
        - crm.lists.write
      - oauth2:
        - crm.lists.read
        - crm.lists.write
      summary: Add and/or Remove Records from a List
      tags:
      - Memberships
  /crm/v3/lists/{listId}:
    delete:
      description: "Delete a list by **ILS list ID**. Lists deleted through this endpoint\
        \ can be restored up to 90-days following the delete. After 90-days, the list\
        \ is purged and can no longer be restored."
      operationId: Remove
      security:
      - private_apps:
        - crm.lists.read
        - crm.lists.write
      - oauth2:
        - crm.lists.read
        - crm.lists.write
      summary: Delete a List
      tags:
      - Lists
    get:
      description: Fetch a single list by **ILS list ID**.
      operationId: "get-/crm/v3/lists/{listId}_getById"
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Fetch List by ID
      tags:
      - Lists
  /crm/v3/lists/{listId}/update-list-filters:
    put:
      description: "Update the filter branch definition of a `DYNAMIC` list. Once\
        \ updated, the list memberships will be re-evaluated and updated to match\
        \ the new definition."
      operationId: "put-/crm/v3/lists/{listId}/update-list-filters_updateListFilters"
      security:
      - private_apps:
        - crm.lists.read
        - crm.lists.write
      - oauth2:
        - crm.lists.read
        - crm.lists.write
      summary: Update List Filter Definition
      tags:
      - Lists
  /crm/v3/lists/search:
    post:
      description: Search lists by list name or page through all lists by providing
        an empty `query` value.
      operationId: post-/crm/v3/lists/search_doSearch
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Search Lists
      tags:
      - Lists
  /crm/v3/lists/{listId}/memberships/add:
    put:
      description: |-
        Add the records provided to the list. Records that do not exist or that are already members of the list are ignored.

        This endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.
      operationId: AddMemberships
      security:
      - private_apps:
        - crm.lists.read
        - crm.lists.write
      - oauth2:
        - crm.lists.read
        - crm.lists.write
      summary: Add Records to a List
      tags:
      - Memberships
  /crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}:
    get:
      description: Fetch a single list by list name and object type.
      operationId: "get-/crm/v3/lists/object-type-id/{objectTypeId}/name/{listName}_getByName"
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Fetch List by Name
      tags:
      - Lists
  /crm/v3/lists/{listId}/memberships/add-from/{sourceListId}:
    put:
      description: |-
        Add all of the records from a *source list* (specified by the `sourceListId`) to a *destination list* (specified by the `listId`). Records that are already members of the *destination list* will be ignored. The *destination* and *source list* IDs must be different. The *destination* and *source lists* must contain records of the same type (e.g. contacts, companies, etc.).

        This endpoint only works for *destination lists* that have a `processingType` of `MANUAL` or `SNAPSHOT`. The *source list* can have any `processingType`.
      operationId: "put-/crm/v3/lists/{listId}/memberships/add-from/{sourceListId}_addAllFromList"
      security:
      - private_apps:
        - crm.lists.read
        - crm.lists.write
      - oauth2:
        - crm.lists.read
        - crm.lists.write
      summary: Add All Records from a Source List to a Destination List
      tags:
      - Memberships
  /crm/v3/lists/:
    get:
      description: Fetch multiple lists in a single request by **ILS list ID**. The
        response will include the definitions of all lists that exist for the `listIds`
        provided.
      operationId: get-/crm/v3/lists/_getAll
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Fetch Multiple Lists
      tags:
      - Lists
    post:
      description: Create a new list with the provided object list definition.
      operationId: Create
      security:
      - oauth2:
        - crm.lists.write
      - private_apps:
        - crm.lists.write
      summary: Create List
      tags:
      - Lists
  /crm/v3/lists/{listId}/restore:
    put:
      description: Restore a previously deleted list by **ILS list ID**. Deleted lists
        are eligible to be restored up-to 90-days after the list has been deleted.
      operationId: "put-/crm/v3/lists/{listId}/restore_restore"
      security:
      - private_apps:
        - crm.lists.read
        - crm.lists.write
      - oauth2:
        - crm.lists.read
        - crm.lists.write
      summary: Restore a List
      tags:
      - Lists
  /crm/v3/lists/{listId}/memberships:
    delete:
      description: |-
        Remove **all** of the records from a list. ***Note:*** *The list is not deleted.*

        This endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.
      operationId: "delete-/crm/v3/lists/{listId}/memberships_removeAll"
      security:
      - private_apps:
        - crm.lists.read
        - crm.lists.write
      - oauth2:
        - crm.lists.read
        - crm.lists.write
      summary: Delete All Records from a List
      tags:
      - Memberships
    get:
      description: |-
        Fetch the memberships of a list in order sorted by the `recordId` of the records in the list.

        The `recordId`s are sorted in *ascending* order if an `after` offset or no offset is provided. If only a `before` offset is provided, then the records are sorted in *descending* order.

        The `after` offset parameter will take precedence over the `before` offset in a case where both are provided.
      operationId: "get-/crm/v3/lists/{listId}/memberships_getPage"
      security:
      - private_apps:
        - crm.lists.read
      - oauth2:
        - crm.lists.read
      summary: Fetch List Memberships Ordered by ID
      tags:
      - Memberships
  /crm/v3/lists/{listId}/memberships/remove:
    put:
      description: |-
        Remove the records provided from the list. Records that do not exist or that are not members of the list are ignored.

        This endpoint only works for lists that have a `processingType` of `MANUAL` or `SNAPSHOT`.
      operationId: RemoveMemberships
      security:
      - private_apps:
        - crm.lists.read
        - crm.lists.write
      - oauth2:
        - crm.lists.read
        - crm.lists.write
      summary: Remove Records from a List
      tags:
      - Memberships
components:
  securitySchemes:
    oauth2:
      flows:
        authorizationCode:
          authorizationUrl: https://app.hubspot.com/oauth/authorize
          scopes:
            crm.lists.read: ' '
            crm.lists.write: ' '
          tokenUrl: https://api.hubapi.com/oauth/v1/token
      type: oauth2
    private_apps:
      in: header
      name: private-app
      type: apiKey
x-hubspot-available-client-libraries:
- PHP
- Node
- Ruby
- Python
x-hubspot-product-tier-requirements:
  marketing: STARTER
  cms: STARTER
x-hubspot-documentation-banner: NONE
