generatorName: go
packageName: lists
outputDir: generated/v3/lists
inputSpec: ./schema/Lists.json
nameMappings:
  setType: SetType_
additionalProperties:
  isGoSubmodule: false
  withGoMod: false
  disallowAdditionalPropertiesIfNotPresent: false
  structPrefix: true
  useOneOfDiscriminatorLookup: true
removeOperationIdPrefix: true
skipValidateSpec: true
enablePostProcessFile: true
